
num_to_station = {
    # Linha azul - 1
    1: "Tucuruvi",
    2: "Parada Inglesa",
    3: "Jardim São Paulo - Ayrton Senna",
    4: "Santana",
    5: "Carandiru",
    6: "Portuguesa Tietê",
    7: "Armênia",
    8: "Tiradentes",
    9: "Luz",
    10: "São Bento",
    11: "Sé",
    12: "Liberdade",
    13: "São Joaquim",
    14: "Vergueiro",
    15: "Paraíso",
    16: "Ana Rosa",
    17: "Vila Mariana",
    18: "Santa Cruz",
    19: "Praça da Árvore",
    20: "Saúde",
    21: "São Judas",
    22: "Conceição",
    23: "Jabaquara",
    
    # Linha verde - 2
    24: "Vila Madalena",
    25: "Sumaré",
    26: "Clínicas",
    27: "Consolação",
    28: "Trianon-Masp",
    29: "Brigadeiro",
    30: "Chácara Klabin",
    31: "Santos-Imigrantes",
    32: "Alto do Ipiranga",
    45: "Sacomã",
    44: "Tamanduateí",
    46: "Vila Prudente",

    # Linha amarela - 4
    33: "República",
    34: "Higienópolis Mackenzie",
    35: "Oscar Freire",
    36: "Fradique Coutinho",
    37: "Faria Lima",
    38: "Pinheiros",
    39: "Butantã",
    40: "São Paulo - Morumbi",
    41: "Vila Sônia",
    42: "",
    43: "",

    # Linha Turquesa - 10
    52: "Brás",
    79: "Juventus - Mooca",
    80: "Ipiranga",
    81: "São Caetano do Sul",
    82: "Utinga",
    83: "Prefeito Saladino",
    84: "Santo André",
    85: "Capuava",
    86: "Mauá",
    87: "Guapituba",
    88: "Ribeirão Pires",
    89: "Rio Grande da Serra",

    # Linha Lilás - 5
    64: "Hospital São Paulo",
    65: "AACD - Servidor",
    66: "Moema",
    67: "Eucaliptos",
    68: "Campo Belo",
    69: "Brooklin",
    70: "Borba Gato",
    71: "Alto da Boa Vista",
    72: "Adolfo Pinheiro",
    73: "Largo Treze",
    74: "Santo Amaro",
    75: "Giovanni Gronchi",
    76: "Vila das Belezas",
    77: "Campo Limpo",
    78: "Capão Redondo",

    # Linha Vermelha - 3
    47: "Palmeiras - Barra Funda",
    48: "Mal. Deodoro",
    49: "Santa Cecília",
    50: "Anhangabaú",
    51: "Pedro II",
    53: "Bresser - Mooca",
    54: "Belém",
    55: "Tatuapé",
    56: "Carrão",
    57: "Penha",
    58: "Vila Matilde",
    59: "Guilhermina Esperança",
    60: "Patriarca - Vila Ré",
    61: "Artur Alvim",
    62: "Corinthians - Itaquera",
    63: "",

    # Linha Esmeralda - 9
    90: "Osasco",
    91: "Pres. Altino",
    92: "Ceasa",
    93: "Villa-Lobos - Jaguaré",
    94: "Cidade Universitária",
    95: "Hebraica - Rebouças",
    96: "Cidade Jardim",
    97: "Vila Olímpia",
    98: "Berrini",
    99: "Morumbi",
    100: "Granja Julieta",
    101: "João Dias",
    102: "Socorro",
    103: "Jurubatuba",
    104: "Autódromo",
    105: "Primavera - Interlagos",
    106: "Grajaú",
    107: "Mendes - Vila Natal",

    # Linha Diamante - 8
    108: "Júlio Prestes",
    109: "Lapa",
    110: "Domingos de Moraes",
    111: "Imperatriz Leopoldina",
    112: "Com. Sampaio",
    113: "Quitaúna",
    114: "Gen. Miguel Costa",
    115: "Carapicuíba",
    116: "Santa Terezinha",
    117: "Antonio João",
    118: "Barueri",
    119: "Jardim Belval",
    120: "Jardim Silveira",
    121: "Jandira",
    122: "Sagrado Coração",
    123: "Eng Cardoso",
    124: "Itapevi",
    125: "Santa Rita",
    126: "Amador Bueno"
}
